<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.3 on win32)" generated="20230621 19:16:03.007" rpa="false" schemaversion="3">
<suite id="s1" name="Conferindo Json" source="C:\Users\guilh\Downloads\robot_framework\python\robot_teste\data_conferencia_teste_api\conferindo_json.robot">
<test id="s1-t1" name="Exemplo: Conferindo JSON complexo" line="10">
<kw name="Confere objetos e sub-objetos do JSON">
<kw name="Pega JSON">
<var>${MEU_JSON_COMPLEXO}</var>
<kw name="Get File" library="OperatingSystem">
<var>${MEU_JSON_COMPLEXO}</var>
<arg>C:\\Users\\guilh\\Downloads\\robot_framework\\python\\robot_teste\\data_conferencia_teste_api/data/output/json_complexo.json</arg>
<doc>Returns the contents of a specified file.</doc>
<msg timestamp="20230621 19:16:03.354" level="INFO" html="true">Getting file '&lt;a href="file://C:\Users\guilh\Downloads\robot_framework\python\robot_teste\data_conferencia_teste_api\data\output\json_complexo.json"&gt;C:\Users\guilh\Downloads\robot_framework\python\robot_teste\data_conferencia_teste_api\data\output\json_complexo.json&lt;/a&gt;'.</msg>
<msg timestamp="20230621 19:16:03.355" level="FAIL">FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guilh\\Downloads\\robot_framework\\python\\robot_teste\\data_conferencia_teste_api\\data\\output\\json_complexo.json'</msg>
<status status="FAIL" starttime="20230621 19:16:03.354" endtime="20230621 19:16:03.355"/>
</kw>
<kw name="To Json">
<var>${MEU_JSON_COMPLEXO}</var>
<arg>${MEU_JSON_COMPLEXO}</arg>
<status status="NOT RUN" starttime="20230621 19:16:03.358" endtime="20230621 19:16:03.358"/>
</kw>
<status status="FAIL" starttime="20230621 19:16:03.354" endtime="20230621 19:16:03.358"/>
</kw>
<kw name="To Json">
<var>${MEU_DICT_ESPERADO}</var>
<arg>${MEU_DICT_ESPERADO}</arg>
<status status="NOT RUN" starttime="20230621 19:16:03.365" endtime="20230621 19:16:03.365"/>
</kw>
<kw name="Dictionary Should Contain Sub Dictionary" library="Collections">
<arg>${MEU_JSON_COMPLEXO["pessoa"]["nome"]}</arg>
<arg>${MEU_DICT_ESPERADO}</arg>
<doc>Fails unless all items in ``dict2`` are found from ``dict1``.</doc>
<status status="NOT RUN" starttime="20230621 19:16:03.365" endtime="20230621 19:16:03.365"/>
</kw>
<kw name="Dictionary Should Contain Item" library="Collections">
<arg>${MEU_JSON_COMPLEXO["pessoa"]["nome"]}</arg>
<arg>apelido</arg>
<arg>May</arg>
<doc>An item of ``key`` / ``value`` must be found in a ``dictionary``.</doc>
<status status="NOT RUN" starttime="20230621 19:16:03.365" endtime="20230621 19:16:03.366"/>
</kw>
<kw name="Dictionary Should Contain Item" library="Collections">
<arg>${MEU_JSON_COMPLEXO["pessoa"]["hobbies"]["livros"][0]}</arg>
<arg>titulo</arg>
<arg>O Símbolo Perdido</arg>
<doc>An item of ``key`` / ``value`` must be found in a ``dictionary``.</doc>
<status status="NOT RUN" starttime="20230621 19:16:03.366" endtime="20230621 19:16:03.366"/>
</kw>
<kw name="Dictionary Should Contain Item" library="Collections">
<arg>${MEU_JSON_COMPLEXO["pessoa"]["hobbies"]["livros"][1]}</arg>
<arg>titulo</arg>
<arg>Sócios no Crime</arg>
<doc>An item of ``key`` / ``value`` must be found in a ``dictionary``.</doc>
<status status="NOT RUN" starttime="20230621 19:16:03.366" endtime="20230621 19:16:03.366"/>
</kw>
<kw name="Dictionary Should Contain Item" library="Collections">
<arg>${MEU_JSON_COMPLEXO["pessoa"]["hobbies"]["livros"][2]}</arg>
<arg>titulo</arg>
<arg>Fortaleza Digital</arg>
<doc>An item of ``key`` / ``value`` must be found in a ``dictionary``.</doc>
<status status="NOT RUN" starttime="20230621 19:16:03.366" endtime="20230621 19:16:03.366"/>
</kw>
<status status="FAIL" starttime="20230621 19:16:03.353" endtime="20230621 19:16:03.366"/>
</kw>
<kw name="Confere listas no JSON">
<status status="NOT RUN" starttime="20230621 19:16:03.367" endtime="20230621 19:16:03.367"/>
</kw>
<status status="FAIL" starttime="20230621 19:16:03.353" endtime="20230621 19:16:03.368">FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guilh\\Downloads\\robot_framework\\python\\robot_teste\\data_conferencia_teste_api\\data\\output\\json_complexo.json'</status>
</test>
<status status="FAIL" starttime="20230621 19:16:03.009" endtime="20230621 19:16:03.370"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Conferindo Json">Conferindo Json</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230621 19:16:03.322" level="ERROR">Error in file 'C:\Users\guilh\Downloads\robot_framework\python\robot_teste\data_conferencia_teste_api\conferindo_json.robot' on line 2: Importing library 'RequestsLibrary' failed: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'
Traceback (most recent call last):
  File "C:\Users\guilh\Downloads\robot_framework\.venv\Lib\site-packages\RequestsLibrary\__init__.py", line 1, in &lt;module&gt;
    from .RequestsKeywords import RequestsKeywords
  File "C:\Users\guilh\Downloads\robot_framework\.venv\Lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 39, in &lt;module&gt;
    class RequestsKeywords(object):
  File "C:\Users\guilh\Downloads\robot_framework\.venv\Lib\site-packages\RequestsLibrary\RequestsKeywords.py", line 41, in RequestsKeywords
    DEFAULT_RETRY_METHOD_LIST = list(copy.copy(Retry.DEFAULT_METHOD_WHITELIST))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PYTHONPATH:
  C:\Users\guilh\Downloads\robot_framework\.venv\Scripts\robot.exe
  C:\Users\guilh\AppData\Local\Programs\Python\Python311\python311.zip
  C:\Users\guilh\AppData\Local\Programs\Python\Python311\DLLs
  C:\Users\guilh\AppData\Local\Programs\Python\Python311\Lib
  C:\Users\guilh\AppData\Local\Programs\Python\Python311
  C:\Users\guilh\Downloads\robot_framework\.venv
  C:\Users\guilh\Downloads\robot_framework\.venv\Lib\site-packages</msg>
</errors>
</robot>
